#!/usr/bin/env python3
"""Generate known-answer-test (KAT) vectors for the esptag crypto core.

This is an INDEPENDENT reference implementation of the primitives in
`main/crypto.c`, written against the public spec (not the C code):

  - KDF:  SP-800-108-style SHA-256 counter mode.
          out = T(1) || T(2) || ... truncated to out_len, where
          T(i) = SHA256( z || counter_be32(i) || info ).
  - crypto_update_sk(sk):      KDF(sk, "update", 32)            (single block)
  - crypto_advance_sk(sk, c):  update applied c times
  - crypto_derive_p(d0, sk):   uv = KDF(sk, "diversify", 72)    (3 blocks)
                               u, v = uv[:36], uv[36:]
                               d_i = (d0*u + v) mod n
                               p_i = x-coord of (d_i * G)        (28-byte BE)

It emits a C header of vectors consumed by the Unity test. Reference EC math
comes from the `cryptography` library, so a bug copied from crypto.c cannot
leak into the expected values.

Run:  python scripts/gen_kat.py > test/main/kat_vectors.h
"""

import hashlib

from cryptography.hazmat.primitives.asymmetric import ec

# secp224r1 group order n, big-endian. Mirrors P224_N in crypto.c.
P224_N = int.from_bytes(
    bytes.fromhex("FFFFFFFFFFFFFFFFFFFFFFFFFFFF16A2E0B8F03E13DD29455C5C2A3D"),
    "big",
)

D_LEN = 28
SK_LEN = 32


def kdf(z: bytes, info: bytes, out_len: int) -> bytes:
    out = b""
    counter = 1
    while len(out) < out_len:
        block = hashlib.sha256(z + counter.to_bytes(4, "big") + info).digest()
        out += block
        counter += 1
    return out[:out_len]


def update_sk(sk: bytes) -> bytes:
    return kdf(sk, b"update", SK_LEN)


def advance_sk(sk: bytes, count: int) -> bytes:
    for _ in range(count):
        sk = update_sk(sk)
    return sk


def derive_p(d0: bytes, sk: bytes) -> bytes:
    uv = kdf(sk, b"diversify", 72)
    u = int.from_bytes(uv[:36], "big")
    v = int.from_bytes(uv[36:], "big")
    d0_int = int.from_bytes(d0, "big")
    d_i = (d0_int * u + v) % P224_N
    priv = ec.derive_private_key(d_i, ec.SECP224R1())
    x = priv.public_key().public_numbers().x
    return x.to_bytes(D_LEN, "big")


# --- Fixed throwaway test inputs (NOT the provisioned seed) -------------------

SK_PREV = bytes(range(SK_LEN))                       # 00 01 02 ... 1f
SK_0 = bytes((0xA0 + i) & 0xFF for i in range(SK_LEN))
D_0 = bytes.fromhex(
    "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c"
)  # 28 bytes, < n
SK_I = bytes((0x37 * i + 0x11) & 0xFF for i in range(SK_LEN))


def c_array(name: str, data: bytes) -> str:
    body = ", ".join(f"0x{b:02x}" for b in data)
    return f"static const uint8_t {name}[{len(data)}] = {{ {body} }};"


def main():
    sk_next = update_sk(SK_PREV)
    sk_2 = advance_sk(SK_0, 2)
    p_i = derive_p(D_0, SK_I)

    print("/* AUTO-GENERATED by scripts/gen_kat.py -- DO NOT EDIT BY HAND. */")
    print("/* Independent reference KAT vectors for the esptag crypto core. */")
    print("#ifndef ESPTAG_KAT_VECTORS_H")
    print("#define ESPTAG_KAT_VECTORS_H")
    print()
    print("#include <stdint.h>")
    print()
    print("/* crypto_update_sk: sk_next = KDF(sk_prev, \"update\", 32) */")
    print(c_array("KAT_SK_PREV", SK_PREV))
    print(c_array("KAT_SK_NEXT", sk_next))
    print()
    print("/* crypto_advance_sk: sk_2 = update^2(sk_0) */")
    print(c_array("KAT_SK_0", SK_0))
    print(c_array("KAT_SK_2", sk_2))
    print()
    print("/* crypto_derive_p: p_i = x((d_0*u + v mod n) * G), uv=KDF(sk_i,\"diversify\",72) */")
    print(c_array("KAT_D_0", D_0))
    print(c_array("KAT_SK_I", SK_I))
    print(c_array("KAT_P_I", p_i))
    print()
    print("#endif /* ESPTAG_KAT_VECTORS_H */")


if __name__ == "__main__":
    main()
